"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Slider } from "@/components/ui/slider"
import { Crown, Save, Upload, Loader2, ImageIcon } from "lucide-react"
import { toast } from "sonner"

const POSITIONS = ["top-left", "top-right", "bottom-left", "bottom-right"] as const
type LogoPosition = (typeof POSITIONS)[number]

interface BrandKit {
  logoUrl: string | null
  logoOpacity: number
  logoPosition: LogoPosition
  primaryColor: string | null
  fontFamily: string | null
  introUrl: string | null
  outroUrl: string | null
}

const EMPTY: BrandKit = {
  logoUrl: null,
  logoOpacity: 0.85,
  logoPosition: "bottom-right",
  primaryColor: null,
  fontFamily: null,
  introUrl: null,
  outroUrl: null,
}

/** Mirrors the server check — the server validates again before it hits ffmpeg. */
const isHex = (v: string) => /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(v)

export function BrandKitPanel() {
  const [kit, setKit] = useState<BrandKit>(EMPTY)
  const [plan, setPlan] = useState<string>("free")
  const [canCustomize, setCanCustomize] = useState(false)
  const [watermarked, setWatermarked] = useState(true)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [uploading, setUploading] = useState(false)
  const fileInput = useRef<HTMLInputElement>(null)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const res = await fetch("/api/brand-kit")
      if (!res.ok) throw new Error("Failed to load brand kit")
      const data = await res.json()
      setPlan(data.plan ?? "free")
      setCanCustomize(!!data.canCustomize)
      setWatermarked(!!data.watermarked)
      if (data.brandKit) setKit({ ...EMPTY, ...data.brandKit })
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to load brand kit")
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    load()
  }, [load])

  const patch = (fields: Partial<BrandKit>) => setKit((k) => ({ ...k, ...fields }))

  const uploadLogo = async (file: File) => {
    setUploading(true)
    try {
      const body = new FormData()
      body.append("file", file)
      const res = await fetch("/api/brand-kit/logo", { method: "POST", body })
      const data = await res.json()
      if (!res.ok) throw new Error(data?.error || "Logo upload failed")
      patch({ logoUrl: data.url })
      toast.success("Logo uploaded — remember to save")
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Logo upload failed")
    } finally {
      setUploading(false)
    }
  }

  const save = async () => {
    if (kit.primaryColor && !isHex(kit.primaryColor)) {
      toast.error("Caption colour must be a hex value like #38bdf8")
      return
    }
    setSaving(true)
    try {
      const res = await fetch("/api/brand-kit", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          logoUrl: kit.logoUrl || null,
          logoOpacity: kit.logoOpacity,
          logoPosition: kit.logoPosition,
          primaryColor: kit.primaryColor || null,
          fontFamily: kit.fontFamily || null,
          introUrl: kit.introUrl || null,
          outroUrl: kit.outroUrl || null,
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data?.error || "Failed to save brand kit")
      toast.success("Brand kit saved — applied to your next render")
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to save brand kit")
    } finally {
      setSaving(false)
    }
  }

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Brand Kit</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">Loading…</CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between gap-4">
          <div>
            <CardTitle>Brand Kit</CardTitle>
            <CardDescription>
              Applied to every render. Branding is enforced on the server, so it also
              applies to videos generated by the worker.
            </CardDescription>
          </div>
          <Badge variant={watermarked ? "secondary" : "default"}>
            {watermarked ? "Watermarked" : "No watermark"}
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-6">
        {!canCustomize && (
          <div className="rounded-lg border border-dashed p-4 flex items-start gap-3">
            <Crown className="h-5 w-5 mt-0.5 text-muted-foreground" />
            <div className="text-sm">
              <p className="font-medium">Custom branding is a paid feature</p>
              <p className="text-muted-foreground">
                You&apos;re on the <strong>{plan}</strong> plan. Free renders carry a
                &ldquo;Made with ForgeVid&rdquo; watermark. Upgrade to add your own logo,
                colours, and intro/outro.
              </p>
            </div>
          </div>
        )}

        <fieldset disabled={!canCustomize} className="space-y-6 disabled:opacity-60">
          {/* Logo */}
          <div className="space-y-3">
            <Label>Logo</Label>
            <div className="flex items-center gap-4">
              <div className="h-16 w-16 rounded border flex items-center justify-center overflow-hidden bg-muted/30">
                {kit.logoUrl ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={kit.logoUrl} alt="Brand logo" className="max-h-full max-w-full" />
                ) : (
                  <ImageIcon className="h-6 w-6 text-muted-foreground" />
                )}
              </div>
              <input
                ref={fileInput}
                type="file"
                accept="image/png,image/jpeg,image/webp,image/svg+xml"
                className="hidden"
                onChange={(e) => {
                  const file = e.target.files?.[0]
                  if (file) uploadLogo(file)
                  e.target.value = ""
                }}
              />
              <Button variant="outline" onClick={() => fileInput.current?.click()} disabled={uploading}>
                {uploading ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <Upload className="h-4 w-4 mr-2" />
                )}
                {kit.logoUrl ? "Replace" : "Upload"}
              </Button>
              {kit.logoUrl && (
                <Button variant="ghost" onClick={() => patch({ logoUrl: null })}>
                  Remove
                </Button>
              )}
            </div>
            <p className="text-xs text-muted-foreground">PNG, JPEG, WebP or SVG. Max 5MB.</p>
          </div>

          {/* Logo placement */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="logoPosition">Logo position</Label>
              <select
                id="logoPosition"
                value={kit.logoPosition}
                onChange={(e) => patch({ logoPosition: e.target.value as LogoPosition })}
                className="w-full rounded-md border bg-background p-2 text-sm"
              >
                {POSITIONS.map((p) => (
                  <option key={p} value={p}>
                    {p.replace("-", " ")}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-2">
              <Label>Logo opacity: {Math.round(kit.logoOpacity * 100)}%</Label>
              <Slider
                value={[kit.logoOpacity * 100]}
                min={10}
                max={100}
                step={5}
                onValueChange={([v]) => patch({ logoOpacity: v / 100 })}
              />
            </div>
          </div>

          {/* Caption colour + font */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="primaryColor">Caption colour</Label>
              <div className="flex items-center gap-2">
                <Input
                  id="primaryColor"
                  placeholder="#38bdf8"
                  value={kit.primaryColor ?? ""}
                  onChange={(e) => patch({ primaryColor: e.target.value || null })}
                />
                <div
                  className="h-9 w-9 shrink-0 rounded border"
                  style={{
                    background:
                      kit.primaryColor && isHex(kit.primaryColor) ? kit.primaryColor : "transparent",
                  }}
                />
              </div>
              {kit.primaryColor && !isHex(kit.primaryColor) && (
                <p className="text-xs text-destructive">Must be #RGB or #RRGGBB.</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="fontFamily">Caption font file</Label>
              <Input
                id="fontFamily"
                placeholder="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
                value={kit.fontFamily ?? ""}
                onChange={(e) => patch({ fontFamily: e.target.value || null })}
              />
              <p className="text-xs text-muted-foreground">
                Absolute path to a .ttf on the render host. Falls back to the system font.
              </p>
            </div>
          </div>

          {/* Intro / outro */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="introUrl">Intro clip URL</Label>
              <Input
                id="introUrl"
                placeholder="https://…/intro.mp4"
                value={kit.introUrl ?? ""}
                onChange={(e) => patch({ introUrl: e.target.value || null })}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="outroUrl">Outro clip URL</Label>
              <Input
                id="outroUrl"
                placeholder="https://…/outro.mp4"
                value={kit.outroUrl ?? ""}
                onChange={(e) => patch({ outroUrl: e.target.value || null })}
              />
            </div>
          </div>

          <p className="text-xs text-muted-foreground">
            Intro and outro are re-encoded to match the video, so any resolution works.
            An intro shifts captions later automatically.
          </p>

          <Button onClick={save} disabled={saving}>
            {saving ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Save className="h-4 w-4 mr-2" />}
            Save brand kit
          </Button>
        </fieldset>
      </CardContent>
    </Card>
  )
}

export default BrandKitPanel
